### ISSUE TITLE
Normalize headers in auth

### ISSUE THREAD

**Issue by yarbelk** [micro/go-platform#32]
https://github.com/micro/go-platform/blob/master/auth/platform.go#L155

When using auth-srv and the HandlerWrapper and ClientWrapper, the metadata map has the key `Authorization`, but the lookup is for `authorization`.

These should be normalized so you don't get lookup errors.

**Comment by asim** [comment]
Here's a fix https://github.com/micro/go-platform/commit/1e631bb6815c2dbabe589649b8d89b5a460c41f5
